### ISSUE TITLE
Review Project Plan with Clean Growth Stakeholders

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-public-reporting#6]
**Description**
Following project planning in [ticket #5](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-public-reporting/5), review proposed plan with CG stakeholders for input.

**Checklist**
- [x] Identify participants
- [x] Book meeting/session
- [x] Hold session: review plan and approach based on feedback
- [x] Circulate revised plan to project team

**Comment by LindsayMacfarlane** [comment]
Great work on the project plan @jaimiebutton !
